export default [
    {
      name: "2 people indoors dinner",
      wearMask: false,
      duration:90,
      nbPeople: 1,
      nbMasked: 0,
      location: "indoors",
      talking: "normal",
      distance: "normal",
      riskProfile: "normal",
    },
    {
        name: "One night stand",
        wearMask:false,
        duration:300,
        nbPeople:1,
        nbMasked:0,
        outdoors:false,
        talking:"normal",
        distance:"close",
        riskProfile:"worker",
    },
    {
        name: "Dance lesson (with fixed partner)",
        wearMask: true,
        duration:60,
        nbPeople: 20,
        nbMasked: 20,
        location: "indoors",
        talking: "normal",
        distance: "normal",
        riskProfile: "normal",
    },
    {
        name: "Concert (seated, with mask)",
        wearMask: true,
        duration:120,
        nbPeople: 10,
        nbMasked: 10,
        location: "indoors",
        talking: "loud",
        distance: "normal",
        riskProfile: "normal",
    },
    {
        name:"Concert (pit, no mask)",
        wearMask: true,
        duration: 120,
        nbPeople: 100,
        nbMasked: 100,
        location: "indoors",
        talking: "loud",
        distance: "normal",
        riskProfile: "normal",
    },
    {
        name:"School/University (one day)",
        nbPeople: 10,
        duration: 480,
        wearMask: true,
        nbMasked: 10,
        location: "indoors",
        distance: "long",
        talking: 'quiet',
        riskProfile: "normal",
    },
    {
        name:"Queue (30mn)",
        wearMask: true,
        duration: 30,
        nbPeople: 4,
        nbMasked: 4,
        location: "indoors",
        talking: "normal",
        distance: "normal",
        riskProfile: "normal",
    },
    {
        name:"Delivery food (with mask)",
        nbPeople:1,
        duration:5,
        wearMask: true,
        nbMasked:1,
        location: "indoors",
        distance:"long",
        talking:'quiet',
        riskProfile: "normal",
    },
    {
        name:"Walk in the park",
        nbPeople:3,
        duration:60,
        wearMask: false,
        nbMasked:0.,
        location: "outdoors",
        distance:"veryLong",
        talking:'quiet',
        riskProfile: "normal",
    },
    {
        name:"2 people outdoors lunch",
        nbPeople:1,
        duration:90,
        wearMask: false,
        nbMasked:0.,
        location: "outdoors",
        distance:"normal",
        talking:'normal',
        riskProfile: "normal",
    },
    {
        name:"Library/Museum (with mask)",
        nbPeople:5,
        duration:120,
        wearMask:true,
        nbMasked:5,
        outdoors:false,
        distance:"long",
        talking:'quiet',
        riskProfile: "normal",
    },
    {
        name:"Grocery shopping",
        nbPeople:10,
        duration:30,
        wearMask:true,
        nbMasked:10,
        outdoors:false,
        distance:"normal",
        talking:'quiet',
        riskProfile: "worker",
    },
    {
        name:"2h picnic",
        nbPeople:5,
        duration:120,
        wearMask:false,
        nbMasked:0,
        location:"outdoors",
        distance:"normal",
        talking:'normal',
        riskProfile: "normal",
    },
    {
        name:"Working in an open space",
        nbPeople:10,
        duration:480,
        wearMask:true,
        nbMasked:10,
        outdoors:false,
        distance:"long",
        talking:'quiet',
        riskProfile: "normal",
    },
    {
        name:"Public transportation (1h)",
        nbPeople:20,
        duration:60,
        wearMask:true,
        nbMasked:20,
        outdoors:false,
        distance:"normal",
        talking:'quiet',
        riskProfile: "normal",
    },
    {
        name:"2h indoors group dinner",
        nbPeople:4,
        duration:120,
        wearMask:false,
        nbMasked:0,
        outdoors:false,
        distance:"normal",
        talking:'normal',
        riskProfile: "normal",
    },
    {
        name:"Cinema/Theater",
        nbPeople:50,
        duration:120,
        wearMask:true,
        nbMasked:50,
        outdoors:false,
        distance:"long",
        talking:'quiet',
        riskProfile: "normal",
    },
    {
        name:"Theater (1st rank)",
        nbPeople:8,
        duration:120,
        wearMask:true,
        nbMasked:0,
        outdoors:false,
        distance:"long",
        talking:'loud',
        riskProfile: "worker",
    },
    {
        name:"3h game night with 4 friends",
        nbPeople:4,
        duration:180,
        wearMask:false,
        nbMasked:0,
        outdoors:false,
        distance:"normal",
        talking:'normal',
        riskProfile: "normal",
    },
    {
        name:"Uber (30mn)",
        nbPeople:1,
        duration:30,
        wearMask:true,
        nbMasked:1,
        location:"car",
        distance:"normal",
        talking:'normal',
        riskProfile: "normal",
    }
  ]
  